/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptsReviewReceiptIdRouteImport } from './routes/receipts/review.$receiptId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReviewReceiptIdRoute = ReceiptsReviewReceiptIdRouteImport.update({
  id: '/receipts/review/$receiptId',
  path: '/receipts/review/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipts/review/$receiptId': typeof ReceiptsReviewReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipts/review/$receiptId': typeof ReceiptsReviewReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipts/review/$receiptId': typeof ReceiptsReviewReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/api/auth/$' | '/receipts/review/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upload' | '/api/auth/$' | '/receipts/review/$receiptId'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/api/auth/$'
    | '/receipts/review/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ReceiptsReviewReceiptIdRoute: typeof ReceiptsReviewReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/review/$receiptId': {
      id: '/receipts/review/$receiptId'
      path: '/receipts/review/$receiptId'
      fullPath: '/receipts/review/$receiptId'
      preLoaderRoute: typeof ReceiptsReviewReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ReceiptsReviewReceiptIdRoute: ReceiptsReviewReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
